### ISSUE TITLE
Fix CSS

### ISSUE THREAD

**Issue by watteh** [watteh/Puckager#21]

**Comment by WickedDeveloper** [comment]
Updated the registration and sign pages.

**Comment by watteh** [comment]
Added Navbar with NGBootstrap

**Comment by watteh** [comment]
Added form classes

**Comment by watteh** [comment]
TO DO:
- Fix option input sizes - need to be larger
- Fix add forms - put into table
- Fix display of "No Tweets" - in Recruit-Social html
- Redo About Page

**Comment by watteh** [comment]
Dave Fixed:
- Option input sizes
- add forms
- about page

**Comment by watteh** [comment]
Fixed - display of "No Tweets"
