### ISSUE TITLE
Investigating Web Crawler for Mongodb with Social Media

### ISSUE THREAD

**Issue by watteh** [watteh/Puckager#7]
Gabriel is looking through web crawlers for social media using MongoDB

**Comment by haocencol** [comment]
@DragoniCode Can you provide details of which framework/libraries you are looking into when implementing the search bot.

**Comment by DragoniCode** [comment]
@haocencol 
The plan is to pull data using the crawler and python-twitter right to the server database
( may use some kind of repeatable script on the server for updating the data), 
then I use pandas and pymongo to store and sort through the data pulled, this data will be what is used by the website to show information based on requirements.
